package com.example.farmacan.main

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import androidx.room.Room
import com.example.farmacan.data.db.AppDatabase
import com.example.farmacan.data.entity.Drug
import com.example.farmacan.ui.nav.NavigationGraph
import com.example.farmacan.ui.theme.FarmacanTheme

class Main : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            FarmacanTheme(dynamicColor = false) {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    val appDatabase: AppDatabase = Room.databaseBuilder(
                        applicationContext,
                        AppDatabase::class.java,
                        "SQLite_DB").fallbackToDestructiveMigration().
                    allowMainThreadQueries().build()
                    val drugsList = listOf(
                        Drug(0, "Paracetamol", "Analgesic", "Fever and pain relief. Paracetamol, also known as acetaminophen in some regions, is a widely utilized analgesic and antipyretic medication renowned for its efficacy in relieving pain and reducing fever. Operating predominantly within the central nervous system, it inhibits the production of prostaglandins, thereby mitigating pain signals and influencing thermoregulation. Commonly available in various formulations, including tablets, liquid suspensions, and over-the-counter combination products, paracetamol is a versatile and accessible remedy for a spectrum of conditions, from mild headaches to post-surgical recovery. Generally considered safe when used as directed, it is a preferred choice for individuals unable to tolerate nonsteroidal anti-inflammatory drugs (NSAIDs) due to gastric concerns. Nonetheless, exceeding recommended doses can lead to severe liver damage, emphasizing the critical importance of adhering to prescribed guidelines. Despite its widespread use, cautious consideration of individual health conditions and potential drug interactions is advised, making paracetamol a foundational yet nuanced component in pain and fever management.", "Box-20", "5.99"),
                        Drug(0, "Ibuprofen", "Anti-inflammatory", "Pain and inflammation relief. Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used to treat mild to moderate pain, and helps to relieve symptoms of arthritis (osteoarthritis, rheumatoid arthritis, or juvenile arthritis), such as inflammation, swelling, stiffness, and joint pain. Ibuprofen, a nonsteroidal anti-inflammatory drug (NSAID), stands as a potent and widely employed analgesic, anti-inflammatory, and antipyretic medication. Mechanistically, it inhibits the activity of cyclooxygenase enzymes, reducing the synthesis of prostaglandins responsible for pain, inflammation, and fever. Available in various forms such as tablets, capsules, and suspensions, ibuprofen is a mainstay in the treatment of conditions ranging from mild to moderate pain, including headaches, muscular aches, and inflammatory disorders. Its versatility extends to addressing fever and inflammatory conditions such as arthritis. While generally well-tolerated when used as directed, precautions are warranted, particularly for individuals with a history of gastrointestinal issues. It is crucial to adhere to prescribed dosages and avoid prolonged use to mitigate the risk of adverse effects, such as gastrointestinal bleeding or renal complications. Ibuprofen, with its rapid onset of action and broad therapeutic scope, remains a cornerstone in pain management and inflammation control, contributing significantly to the well-being of countless individuals worldwide.", "Box-10", "7.49"),
                        Drug(0, "Omeprazole", "Proton Pump Inhibitor", "Acid reflux treatment. Omeprazole is used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes. It relieves symptoms such as heartburn, difficulty swallowing, and persistent cough. Omeprazole, a proton pump inhibitor (PPI), is a pharmacological stalwart renowned for its efficacy in the management of gastrointestinal disorders. Operating by irreversibly inhibiting the proton pump in gastric parietal cells, it suppresses gastric acid secretion, making it a cornerstone in the treatment of conditions such as gastroesophageal reflux disease (GERD), peptic ulcers, and Zollinger-Ellison syndrome. Available in various formulations, including capsules and oral suspensions, omeprazole provides sustained relief from acid-related disorders. Its significance extends to the prevention of ulcers associated with prolonged NSAID use. While generally well-tolerated, prolonged usage may pose a risk of bone fractures and Clostridium difficile infections, warranting judicious prescribing. Omeprazole's pivotal role in alleviating gastrointestinal distress underscores its importance in enhancing the quality of life for individuals grappling with acid-related disorders, marking it as a pharmacological linchpin in gastroenterological therapeutics.", "Box-20", "9.99"),
                        Drug(0, "Loratadine", "Antihistamine", "Allergy relief. Loratadine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching. Loratadine, a second-generation antihistamine, stands as a widely utilized medication in the management of allergic conditions. Renowned for its effectiveness in alleviating symptoms associated with seasonal allergies, hay fever, and chronic idiopathic urticaria, loratadine operates by blocking the action of histamine, a key mediator of allergic responses. Available in various formulations, including tablets, chewable tablets, and syrup, it offers flexibility for individuals of different age groups. Unlike earlier antihistamines, loratadine is celebrated for its non-sedating properties, allowing for daytime use without the drowsiness commonly associated with some allergy medications. Its mechanism of action and long duration of effect make it a preferred choice for those seeking relief from sneezing, itching, and nasal congestion due to allergic reactions. While generally well-tolerated, it is essential to adhere to recommended dosages and consult healthcare professionals, particularly for individuals with pre-existing medical conditions or those taking other medications to avoid potential interactions. Loratadine's role as a reliable and non-drowsy antihistamine underscores its significance in enhancing the quality of life for individuals grappling with allergic symptoms.", "Box-30","3.99"),
                        Drug(0, "Amoxicillin", "Antibiotic", "Bacterial infection treatment. Amoxicillin is a penicillin antibiotic that fights bacteria. It is used to treat many different types of infections caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract. Amoxicillin, a prominent member of the beta-lactam antibiotic class, serves as a cornerstone in the therapeutic arsenal against bacterial infections. Leveraging its mechanism of action by disrupting the synthesis of bacterial cell walls, amoxicillin exhibits a commendable breadth of antimicrobial activity, targeting both Gram-positive and Gram-negative bacteria. Widely prescribed for an array of infections, including respiratory tract, urinary tract, and skin infections, amoxicillin's versatility extends across diverse clinical scenarios. Available in various formulations, such as oral tablets, capsules, and liquid suspensions, it accommodates flexible dosing for patients of different age groups. While generally well-tolerated, common side effects encompass gastrointestinal disturbances, with rare instances of allergic reactions necessitating vigilance. The emergence of antibiotic resistance underscores the importance of judicious prescribing practices. Precautions, including avoidance in individuals with known penicillin allergies, are essential, and adherence to prescribed regimens is paramount to mitigate resistance development. Amoxicillin stands as a stalwart ally in modern medicine, exemplifying its pivotal role in the effective management of bacterial infections, albeit with the imperative need for responsible use.", "Box-10","12.99"),
                        Drug(0, "Azithromycin", "Antibiotic", "Bacterial infection treatment. Azithromycin is used to treat a wide variety of bacterial infections. It is a macrolide-type antibiotic. It works by stopping the growth of bacteria. Azithromycin, a broad-spectrum macrolide antibiotic, stands as a vital agent in the therapeutic arsenal against various bacterial infections. Renowned for its efficacy in treating respiratory tract infections, skin and soft tissue infections, and sexually transmitted diseases, azithromycin works by inhibiting bacterial protein synthesis, leading to the disruption of bacterial growth. Its unique pharmacokinetic profile allows for a shorter treatment course compared to some other antibiotics, making it a convenient and preferred choice for both healthcare providers and patients. Available in various formulations, including tablets, oral suspensions, and intravenous solutions, azithromycin offers flexibility in administration. Noteworthy is its extensive tissue penetration, contributing to its effectiveness against intracellular pathogens. Despite its generally favorable safety profile, cautious use and adherence to prescribed regimens are essential to prevent antibiotic resistance and potential side effects. Azithromycin's role in combating a diverse range of bacterial infections underscores its significance in contemporary medical practice, providing a reliable and versatile option for patients in need of antimicrobial therapy.", "Box-20","14.99"),
                        Drug(0, "Simvastatin", "Statins", "Cholesterol management. Simvastatin is used along with a proper diet to help lower 'bad' cholesterol and fats (such as LDL, triglycerides) and raise 'good' cholesterol (HDL) in the blood. Simvastatin, a widely prescribed statin medication, plays a pivotal role in managing hyperlipidemia and reducing cardiovascular risk. As a 3-hydroxy-3-methylglutaryl coenzyme A (HMG-CoA) reductase inhibitor, simvastatin exerts its therapeutic effects by lowering cholesterol synthesis in the liver, subsequently decreasing circulating levels of low-density lipoprotein (LDL) cholesterol, often referred to as bad cholesterol. This lipid-lowering action not only proves effective in treating conditions such as hypercholesterolemia but also has substantial implications for preventing cardiovascular events. Simvastatin has demonstrated efficacy in reducing the incidence of coronary heart disease, stroke, and overall mortality in individuals with or at risk for atherosclerotic cardiovascular disease. Available in oral tablet form, simvastatin is often prescribed as part of a comprehensive approach to cardiovascular risk reduction, encompassing lifestyle modifications and other pharmacological interventions. Adherence to prescribed dosages, routine monitoring of lipid levels, and consideration of potential drug interactions are crucial aspects of ensuring the safe and effective use of simvastatin in optimizing cardiovascular health for individuals with dyslipidemia.", "Box-20","8.99"),
                        Drug(0, "Citalopram", "Antidepressant", "Depression treatment. Citalopram is used to treat depression. It may improve your energy level and feelings of well-being. Citalopram is known as a selective serotonin reuptake inhibitor (SSRI). Citalopram, an antidepressant belonging to the selective serotonin reuptake inhibitor (SSRI) class, stands as a key therapeutic agent in the management of major depressive disorder and other mood disorders. Functioning by inhibiting the reuptake of serotonin in the brain, citalopram enhances serotonin levels, a neurotransmitter implicated in mood regulation. This pharmacological action alleviates depressive symptoms and promotes a sense of well-being. Often prescribed in tablet or oral solution form, citalopram is known for its generally favorable tolerability and ease of use. The medication's effectiveness extends beyond depression, as it can also be employed in the treatment of panic disorder and obsessive-compulsive disorder. However, cautious prescribing is essential, taking into consideration individual patient characteristics and potential interactions with other medications. Regular monitoring and communication between healthcare providers and patients are crucial to tailor treatment plans and optimize therapeutic outcomes while minimizing potential side effects associated with citalopram use.", "Box-10","10.49"),
                        Drug(0, "Amlodipine", "Calcium channel blocker", "Hypertension treatment. Amlodipine is used with or without other medications to treat high blood pressure. Lowering high blood pressure helps prevent strokes, heart attacks, and kidney problems. Amlodipine, a long-acting dihydropyridine calcium channel blocker, stands as a cornerstone in the management of hypertension and certain cardiovascular conditions. By inhibiting calcium influx into vascular smooth muscle cells, amlodipine leads to vasodilation, reducing peripheral vascular resistance and lowering blood pressure. Widely prescribed in oral tablet form, amlodipine is esteemed for its efficacy, long duration of action, and once-daily dosing convenience. Beyond its antihypertensive effects, amlodipine demonstrates utility in treating angina, contributing to improved coronary blood flow and reduced ischemic symptoms. While generally well-tolerated, cautious monitoring is essential, especially in individuals with pre-existing cardiac conditions or those taking other medications. Amlodipine's role in cardiovascular health underscores its significance in addressing hypertension and related disorders, promoting optimal blood pressure control and mitigating the risk of cardiovascular events.", "Box-30","7.99"),
                        Drug(0, "Warfarin", "Anticoagulant", "Blood clot prevention. Warfarin is used to prevent blood clots from forming or growing larger in your blood and blood vessels. It is prescribed for people with certain types of irregular heartbeats, people with prosthetic (replacement or mechanical) heart valves, and people who have suffered a heart attack. Warfarin, an oral anticoagulant, plays a crucial role in preventing and managing thromboembolic events by inhibiting the synthesis of vitamin K-dependent clotting factors in the liver. Widely prescribed for conditions such as atrial fibrillation, deep vein thrombosis, and pulmonary embolism, warfarin effectively interferes with the coagulation cascade, reducing the risk of blood clots. Administered in tablet form, its anticoagulant effects require careful monitoring, typically through international normalized ratio (INR) testing, to maintain therapeutic levels while avoiding bleeding complications. Warfarin's narrow therapeutic window necessitates individualized dosing, and interactions with certain foods, drugs, and health conditions require vigilant management. Despite the advent of newer anticoagulants, warfarin remains a mainstay in anticoagulation therapy, offering a well-established and cost-effective option for patients requiring long-term anticoagulation with careful consideration of its potential risks and benefits.", "Box-10", "5.49")
                    )
                    if (appDatabase.getDrugDao().getAll().isEmpty()) {
                        drugsList.forEach {
                            appDatabase.getDrugDao().insert(it)
                        }
                    }
                    appDatabase.getDrugDao().getAll().forEach {
                        println(it)
                    }
                    NavigationGraph(appDatabase, applicationContext)
                }
            }
        }
    }
}
